import js from "@eslint/js";
import tseslint from "typescript-eslint";
import reactHooks from "eslint-plugin-react-hooks";

/**
 * Lint rules for the site, the dashboard and the API.
 *
 * **Deliberately narrow.** This project had no linter until now, and ~28'000
 * lines were written without one — so a maximal config would open with several
 * hundred findings, which is a wall nobody reads and a diff that buries the
 * real work. The rules here are the ones that catch *bugs*, not the ones that
 * catch style: style is Prettier's job and is not argued about.
 *
 * Two rules earn their place from this codebase's own history rather than from
 * a preset:
 *
 * - `react-hooks/exhaustive-deps` is a **warning**, not an error. `useAsync`
 *   takes its dependencies as an explicit array precisely because the loader is
 *   a fresh closure every render, and its own call sites carry a documented
 *   disable. Making this an error would turn a deliberate design into a build
 *   failure.
 * - `no-floating-promises` is off. It needs type-aware linting across two
 *   separate TypeScript programs, and the project already marks intent with
 *   `void` at every deliberate fire-and-forget (`AuditService.record`,
 *   `void this.notify(...)`). Worth turning on with a type-aware config later;
 *   not worth the build time now.
 *
 * Generated files are ignored rather than fixed — `SchnittGuglera.tsx`,
 * `SchnittAA.tsx` and `src/generated/` come out of the Python chain in `cad/`
 * and are overwritten by it, so a lint fix there is lost on the next run.
 */
export default tseslint.config(
  {
    ignores: [
      "dist/**",
      "server/dist/**",
      "**/node_modules/**",
      "cad/**",
      "var/**",
      // Generated by cad/. Hand edits are overwritten; see CLAUDE.md.
      "src/generated/**",
      "src/components/SchnittGuglera.tsx",
      "src/components/SchnittAA.tsx",
    ],
  },

  js.configs.recommended,
  ...tseslint.configs.recommended,

  {
    files: ["**/*.{ts,tsx}"],
    plugins: { "react-hooks": reactHooks },
    rules: {
      ...reactHooks.configs.recommended.rules,

      // See the note above.
      "react-hooks/exhaustive-deps": "warn",

      /**
       * The React Compiler rules, all as warnings.
       *
       * They fire 21 times across code that predates them, and every instance
       * checked so far is a pattern this codebase chose and documented rather
       * than a defect: `SiteSearch` resets its keyboard cursor when the query
       * changes so Enter cannot fire on a result that is no longer shown;
       * `ConfirmDialog` clears the typed confirmation when it reopens;
       * `Sidebar` reads a ref during render to compare history against the
       * previous value without re-subscribing.
       *
       * Each is worth revisiting — several would be cleaner derived from state
       * during render — but turning 21 deliberate, commented decisions into
       * build failures on the day a linter arrives is how a linter gets
       * disabled. They are warnings so they are visible and countable, and the
       * count is a backlog rather than a wall.
       */
      "react-hooks/set-state-in-effect": "warn",
      "react-hooks/refs": "warn",
      "react-hooks/use-memo": "warn",

      // An unused variable is usually a leftover from an edit, and `tsc`
      // already fails the build on one (`noUnusedLocals`). This aligns the two
      // and adds the `_`-prefix escape the compiler flag does not offer.
      "@typescript-eslint/no-unused-vars": [
        "error",
        { argsIgnorePattern: "^_", varsIgnorePattern: "^_", caughtErrors: "none" },
      ],

      // `any` defeats the point of a strict codebase, but this code has very
      // little of it and the few uses are at genuine boundaries — a warning
      // says "justify this" without failing a build over it.
      "@typescript-eslint/no-explicit-any": "warn",

      // `!` on something the compiler cannot prove. Common and correct in the
      // DTOs (`key!: string`), so not an error.
      "@typescript-eslint/no-non-null-assertion": "off",

      // Catches `if (promise)` and a missing `await` on a call whose result is
      // discarded in a condition — cheap, no type information needed.
      "no-constant-binary-expression": "error",

      // `==` against null is idiomatic and deliberate in a few places
      // (`value == null` covering both), so only the non-null cases are errors.
      eqeqeq: ["error", "always", { null: "ignore" }],
    },
  },

  {
    // The API is CommonJS with decorators and Node globals.
    files: ["server/**/*.ts"],
    languageOptions: {
      globals: { process: "readonly", console: "readonly", Buffer: "readonly", __dirname: "readonly" },
    },
    rules: {
      // Nest DI declares constructor parameters that are only used through
      // `this`, and the empty-class-member pattern is how a module is written.
      "@typescript-eslint/no-empty-object-type": "off",
    },
  },

  {
    files: ["**/*.test.ts", "**/*.test.tsx"],
    rules: {
      // Tests reach into shapes on purpose.
      "@typescript-eslint/no-explicit-any": "off",
    },
  },
);
