import { Injectable, Logger } from "@nestjs/common";
import { ConfigService } from "@nestjs/config";
import { createReadStream, promises as fs } from "node:fs";
import { dirname, join, resolve, sep } from "node:path";
import type { Readable } from "node:stream";

/**
 * Where media bytes live.
 *
 * An interface with one implementation, which is normally a smell — the reason
 * it is here is that the storage target is the single thing most likely to
 * change when this is deployed (local disk on a VM, S3 or Azure Blob on a
 * platform), and it is reachable from exactly one place. Swapping it later
 * then means writing one class, not finding every `fs.writeFile` in the
 * codebase.
 */
export interface StorageAdapter {
  put(key: string, data: Buffer, contentType: string): Promise<void>;
  get(key: string): Promise<Buffer>;
  stream(key: string): Promise<Readable>;
  delete(key: string): Promise<void>;
  exists(key: string): Promise<boolean>;
  /** Public URL, if the adapter serves one directly. */
  url(key: string): string;
}

@Injectable()
export class LocalStorageAdapter implements StorageAdapter {
  private readonly logger = new Logger(LocalStorageAdapter.name);
  private readonly root: string;
  private readonly publicPath: string;

  constructor(private readonly config: ConfigService) {
    this.root = resolve(config.get<string>("MEDIA_ROOT") ?? "./var/media");
    this.publicPath = config.get<string>("MEDIA_PUBLIC_PATH") ?? "/media";
  }

  /**
   * Resolves a storage key to a path, refusing to leave the root.
   *
   * Keys are generated by the service, not supplied by callers — but this is
   * the one function where a traversal would become arbitrary file write, so
   * it checks rather than trusting that invariant to hold forever.
   */
  private pathFor(key: string): string {
    const full = resolve(join(this.root, key));
    if (full !== this.root && !full.startsWith(this.root + sep)) {
      throw new Error(`Storage key escapes the media root: ${key}`);
    }
    return full;
  }

  async put(key: string, data: Buffer): Promise<void> {
    const path = this.pathFor(key);
    await fs.mkdir(dirname(path), { recursive: true });
    await fs.writeFile(path, data);
  }

  get(key: string): Promise<Buffer> {
    return fs.readFile(this.pathFor(key));
  }

  async stream(key: string): Promise<Readable> {
    return createReadStream(this.pathFor(key));
  }

  async delete(key: string): Promise<void> {
    try {
      await fs.unlink(this.pathFor(key));
    } catch (err) {
      // A missing file is the desired end state, not a failure. Anything else
      // is worth knowing about but must not fail the request — the database
      // row is already gone by this point.
      if ((err as NodeJS.ErrnoException).code !== "ENOENT") {
        this.logger.warn(`Konnte ${key} nicht löschen: ${(err as Error).message}`);
      }
    }
  }

  async exists(key: string): Promise<boolean> {
    try {
      await fs.access(this.pathFor(key));
      return true;
    } catch {
      return false;
    }
  }

  url(key: string): string {
    return `${this.publicPath}/${key}`;
  }
}

export const STORAGE = Symbol("STORAGE");
